
import { BASE_URL, getCookie } from "@/helper/common";
import axios from "axios";

/**
 * ReportsServices
 * Description: Provides methods to fetch farmer and buyer-related reports from the API.
 */

export default class ReportsServices {

    // === Farmer Reports ===

    /**
     * Fetches the number of products associated with the farmer.
     * @returns {Promise} Axios response promise containing the product count.
     */
    static async farmerNoOfProduct() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/noOfProduct`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    /**
     * Fetches the total revenue generated by the farmer.
     * @returns {Promise} Axios response promise containing the revenue data.
     */
    static async farmerTotalRevenue() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/totalRevenue`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    /**
     * Fetches the total number of orders for the farmer.
     * @returns {Promise} Axios response promise containing the order count.
     */
    static async farmerNoOfOrders() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/noOfOrders`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    /**
     * Fetches the latest orders placed with the farmer.
     * @returns {Promise} Axios response promise containing the latest orders.
     */
    static async farmerLeastOrder() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/latestOrders`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    /**
    * Fetches the total sales data product-wise for the farmer.
    * @returns {Promise} Axios response promise containing the sales data.
    */
    static async totalSaleProductWise() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/totalsale`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    /**
    * Fetches the farmer's revenue for a specific time period.
    * @param {Object} data - Contains startDate, endDate, and duration for filtering.
    * @param {string} data.startDate - The start date for the report.
    * @param {string} data.endDate - The end date for the report.
    * @param {string} data.duration - The duration filter for the report.
    * @returns {Promise} Axios response promise containing the revenue data.
    */
    static async farmerRevenue(data) {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/farmer/revenue?startDate=${data?.startDate}&endDate=${data?.endDate}&duration=${data?.duration}`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    // === Buyer Reports ===

    static async PurchaseHistory() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/buyer/purchaseHistory`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    static async TransportDetails() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/buyer/transportDetail`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }

    static async frequentlySelectedTransporter() {
        const token = getCookie("token");
        const url = `${BASE_URL}/report/buyer/frequentlySelectedTransporter`
        return axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });
    }
}